name: Cypres Tests

on: [push]

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latests
    steps:
      - name: Get code
        uses: actions/checkout@v4.1.5

      - name: Install dependencies
        run: yarn install

      - name: Run E2E tests
        run: yarn cypress run
    
