name: Cypress Cloud

on: 
  workflow_dispatch:
    inputs:
      cli:
        description: Run by cypress command line
        default: cypress/e2e/*
jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4.1.5

      - name: Cypress run
        run:  cypress-io/github-action@v6.5.0
        with: 
          install-command: yarn install
          browser: electron
          record: true
          group: UI Electron
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: 6ebed216-d372-435f-9fb1-82393d1fe526
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          
